# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 290bd3b9d102ed4ac6d1537e147ed12caf864803526a06812a52b7add8b89d3a7a71dbb7b51838570442356c5aa2aa3d99b91bec783424b4bd59ede34522d6e8

test:
  secret_key_base: 58f5ba3f9676d1c6e8c61ff23aa679e9deef66526ad13c0ca492cc79cbee76d5d3e4f60625ad69c3b201bd89a55c8367effdfad92ebbd263a1c62c4dc61d4aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
